### ISSUE TITLE
Request: Prevent rotation

### ISSUE THREAD

**Issue by DaGLiMiOuX** [godswearhats/jquery-ui-rotatable#52] opened 2016-08-04 10:29 UTC
Hi again!

Would be nice to set a `return false;` on the `start` function event to stop rotation if a condition is met. I'm trying to do it now, but it doesn't stop rotating the element. It just prevents the custom function execution, but not the rotation (like with jQuery UI resizable).

Thanks in advance.

Best regards,
Daglimioux.

**Comment by godswearhats** [comment] 2017-04-26 18:23
Duplicate of another bug, which is now fixed.

**Closed by godswearhats** 2017-04-26 18:23 UTC
